<template>
    <div>
        <a name="workwithus"></a>
        <div id="vm-workwithus" class="black color-teal">
            <div class="container">
                <div class="row">
                    
                        <div class="gf_browser_unknown gform_wrapper" id="gform_wrapper_2"><a id="gf_2" class="gform_anchor"></a><form method="post" enctype="multipart/form-data" target="gform_ajax_frame_2" id="gform_2" action="/#gf_2">
                                <div class="gform_heading">
                                    <h3 class="gform_title">LET'S CONNECT</h3>
                                </div>
                                <div class="gform_body"><ul id="gform_fields_2" class="gform_fields top_label form_sublabel_above description_above"><li id="field_2_42" class="gfield gfield_contains_required field_sublabel_above field_description_above gfield_visibility_visible"><label class="gfield_label" for="input_2_42">Tell Us What You're Interested In:<span class="gfield_required">*</span></label><div class="ginput_container ginput_container_select"><div class="select"><select name="input_42" id="input_2_42" class="large gfield_select s-hidden" aria-required="true" aria-invalid="false"><option value="" selected="selected" class="gf_placeholder">Please Select:</option><option value="Full Service: Creative, Strategy, Media" selected="selected">Full Service: Creative, Strategy, Media</option><option value="Consulting Offerings: 4Ds, VaynerMentors">Consulting Offerings: 4Ds, VaynerMentors</option><option value="Small to Midsize Business Offerings">Small to Midsize Business Offerings</option><option value="Other VaynerMedia Services: VaynerTalent, VaynerExperience, Etc.">Other VaynerMedia Services: VaynerTalent, VaynerExperience, Etc.</option><option value="Studio/Production">Studio/Production</option><option value="Press &amp; Other Inquires">Press &amp; Other Inquires</option></select><div class="styledSelect">Please Select:</div><ul class="options"><li rel="">Please Select:</li><li rel="Full Service: Creative, Strategy, Media">Full Service: Creative, Strategy, Media</li><li rel="Consulting Offerings: 4Ds, VaynerMentors">Consulting Offerings: 4Ds, VaynerMentors</li><li rel="Small to Midsize Business Offerings">Small to Midsize Business Offerings</li><li rel="Other VaynerMedia Services: VaynerTalent, VaynerExperience, Etc.">Other VaynerMedia Services: VaynerTalent, VaynerExperience, Etc.</li><li rel="Studio/Production">Studio/Production</li><li rel="Press &amp; Other Inquires">Press &amp; Other Inquires</li></ul></div></div></li><li id="field_2_3" class="gfield col-sm-6 gfield_contains_required field_sublabel_above field_description_above gfield_visibility_visible"><label class="gfield_label" for="input_2_3">Name:<span class="gfield_required">*</span></label><div class="ginput_container ginput_container_text"><input name="input_3" id="input_2_3" type="text" value="" class="medium" aria-required="true" aria-invalid="false"></div></li><li id="field_2_4" class="gfield col-sm-6 gfield_contains_required field_sublabel_above field_description_above gfield_visibility_visible"><label class="gfield_label" for="input_2_4">Email:<span class="gfield_required">*</span></label><div class="ginput_container ginput_container_email">
                                    <input name="input_4" id="input_2_4" type="text" value="" class="medium" aria-required="true" aria-invalid="false">
                                </div></li><li id="field_2_8" class="gfield col-sm-6 gfield_contains_required field_sublabel_above field_description_above gfield_visibility_visible"><label class="gfield_label" for="input_2_8">Company Name:<span class="gfield_required">*</span></label><div class="ginput_container ginput_container_text"><input name="input_8" id="input_2_8" type="text" value="" class="medium" aria-required="true" aria-invalid="false"></div></li><li id="field_2_33" class="gfield form-break gfield_html gfield_html_formatted gfield_no_follows_desc field_sublabel_above field_description_above gfield_visibility_visible"></li><li id="field_2_20" class="gfield field_sublabel_above field_description_above gfield_visibility_visible"><label class="gfield_label" for="input_2_20">What Can We Do For You?</label><div class="ginput_container ginput_container_textarea"><textarea name="input_20" id="input_2_20" class="textarea large" aria-invalid="false" rows="10" cols="50"></textarea></div></li><li id="field_2_37" class="gfield col-sm-6 col-xs-12 gfield_contains_required field_sublabel_above field_description_above gfield_visibility_visible"><label class="gfield_label"><span class="gfield_required">*</span></label><div class="ginput_container ginput_container_checkbox"><ul class="gfield_checkbox" id="input_2_37"><li class="gchoice_2_37_1">
                                        <input name="input_37.1" type="checkbox" value="<p><span class='asterisk-red'>*</span> Yes, I'd also like to receive information about additional products or services that may be of interest to me. Information submitted through this form is subject to our <a href=&quot;/privacy-policy&quot;>Privacy Policy</a></p>" id="choice_2_37_1">
                                        <label for="choice_2_37_1" id="label_2_37_1"><p><span class="asterisk-red">*</span> Yes, I'd also like to receive information about additional products or services that may be of interest to me. Information submitted through this form is subject to our <a href="/privacy-policy">Privacy Policy</a></p></label>
                                    </li></ul></div></li><li id="field_2_41" class="gfield col-xs-12 col-sm-6 message-block gfield_html gfield_html_formatted gfield_no_follows_desc field_sublabel_above field_description_above gfield_visibility_visible"><p><a href="https://boards.greenhouse.io/vaynermedia" target="_blank">VaynerMedia Careers</a><br><a href="https://vaynerx.com/" target="_blank">VaynerX</a></p> </li><li id="field_2_43" class="gfield gform_validation_container field_sublabel_above field_description_above gfield_visibility_"><label class="gfield_label" for="input_2_43">Comments</label><div class="gfield_description">This field is for validation purposes and should be left unchanged.</div><div class="ginput_container"><input name="input_43" id="input_2_43" type="text" value=""></div></li>
                                    </ul></div>
                <div class="gform_footer top_label"> <input type="submit" id="gform_submit_button_2" class="gform_button button" value="Submit" onclick="if(window[&quot;gf_submitting_2&quot;]){return false;}  window[&quot;gf_submitting_2&quot;]=true;  " onkeypress="if( event.keyCode == 13 ){ if(window[&quot;gf_submitting_2&quot;]){return false;} window[&quot;gf_submitting_2&quot;]=true;  jQuery(&quot;#gform_2&quot;).trigger(&quot;submit&quot;,[true]); }"> <input type="hidden" name="gform_ajax" value="form_id=2&amp;title=1&amp;description=&amp;tabindex=0">
                    <input type="hidden" class="gform_hidden" name="is_submit_2" value="1">
                    <input type="hidden" class="gform_hidden" name="gform_submit" value="2">
                    
                    <input type="hidden" class="gform_hidden" name="gform_unique_id" value="">
                    <input type="hidden" class="gform_hidden" name="state_2" value="WyJbXSIsImY1Njg0M2M0YjE3M2FhOGEyYjJmOTRjOTEwMjZkM2MwIl0=">
                    <input type="hidden" class="gform_hidden" name="gform_target_page_number_2" id="gform_target_page_number_2" value="0">
                    <input type="hidden" class="gform_hidden" name="gform_source_page_number_2" id="gform_source_page_number_2" value="1">
                    <input type="hidden" name="gform_field_values" value="">
                    
                </div>
                                </form>
                                </div>
                        <iframe style="display:none;width:0px;height:0px;" src="about:blank" name="gform_ajax_frame_2" id="gform_ajax_frame_2">This iframe contains the logic required to handle AJAX powered Gravity Forms.</iframe>
                        <script type="text/javascript">jQuery(document).ready(function($){gformInitSpinner( 2, 'https://vaynermedia.com/wp-content/plugins/gravityforms/images/spinner.gif' );jQuery('#gform_ajax_frame_2').load( function(){var contents = jQuery(this).contents().find('*').html();var is_postback = contents.indexOf('GF_AJAX_POSTBACK') >= 0;if(!is_postback){return;}var form_content = jQuery(this).contents().find('#gform_wrapper_2');var is_confirmation = jQuery(this).contents().find('#gform_confirmation_wrapper_2').length > 0;var is_redirect = contents.indexOf('gformRedirect(){') >= 0;var is_form = form_content.length > 0 && ! is_redirect && ! is_confirmation;if(is_form){jQuery('#gform_wrapper_2').html(form_content.html());if(form_content.hasClass('gform_validation_error')){jQuery('#gform_wrapper_2').addClass('gform_validation_error');} else {jQuery('#gform_wrapper_2').removeClass('gform_validation_error');}setTimeout( function() { /* delay the scroll by 50 milliseconds to fix a bug in chrome */ jQuery(document).scrollTop(jQuery('#gform_wrapper_2').offset().top); }, 50 );if(window['gformInitDatepicker']) {gformInitDatepicker();}if(window['gformInitPriceFields']) {gformInitPriceFields();}var current_page = jQuery('#gform_source_page_number_2').val();gformInitSpinner( 2, 'https://vaynermedia.com/wp-content/plugins/gravityforms/images/spinner.gif' );jQuery(document).trigger('gform_page_loaded', [2, current_page]);window['gf_submitting_2'] = false;}else if(!is_redirect){var confirmation_content = jQuery(this).contents().find('.GF_AJAX_POSTBACK').html();if(!confirmation_content){confirmation_content = contents;}setTimeout(function(){jQuery('#gform_wrapper_2').replaceWith(confirmation_content);jQuery(document).scrollTop(jQuery('#gf_2').offset().top);jQuery(document).trigger('gform_confirmation_loaded', [2]);window['gf_submitting_2'] = false;}, 50);}else{jQuery('#gform_2').append(contents);if(window['gformRedirect']) {gformRedirect();}}jQuery(document).trigger('gform_post_render', [2, current_page]);} );} );</script><script type="text/javascript"> if(typeof gf_global == 'undefined') var gf_global = {"gf_currency_config":{"name":"U.S. Dollar","symbol_left":"$","symbol_right":"","symbol_padding":"","thousand_separator":",","decimal_separator":".","decimals":2},"base_url":"https:\/\/vaynermedia.com\/wp-content\/plugins\/gravityforms","number_formats":[],"spinnerUrl":"https:\/\/vaynermedia.com\/wp-content\/plugins\/gravityforms\/images\/spinner.gif"};jQuery(document).bind('gform_post_render', function(event, formId, currentPage){if(formId == 2) {if(typeof Placeholders != 'undefined'){
                                Placeholders.enable();
                            }} } );jQuery(document).bind('gform_post_conditional_logic', function(event, formId, fields, isInit){} );</script><script type="text/javascript"> jQuery(document).ready(function(){jQuery(document).trigger('gform_post_render', [2, 1]) } ); </script>            <br>
                </div>
            </div>
            <div class="modal-overlay"></div>
            <div class="modal-container">
                <div class="form-popup">Reminder: This workshop is $10,000 per seat. If that doesn't work for you, please look into the other options on this page. Thanks!
                    <div class="btn btn-teal" id="got-it">Got it!</div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
    export default {
        
    }
</script>

<style lang="scss" scoped>

</style>